# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_models.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'data_models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_models.proto\x12\x0e\x64\x61ta_models.v1\"T\n\nRedditData\x12\x11\n\tsubreddit\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x16\n\x0eunix_timestamp\x18\x04 \x01(\x03\"e\n\x0e\x41nalysisResult\x12,\n\x08raw_data\x18\x01 \x01(\x0b\x32\x1a.data_models.v1.RedditData\x12\x12\n\ncategories\x18\x02 \x03(\t\x12\x11\n\tsentiment\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REDDITDATA']._serialized_start=37
  _globals['_REDDITDATA']._serialized_end=121
  _globals['_ANALYSISRESULT']._serialized_start=123
  _globals['_ANALYSISRESULT']._serialized_end=224
# @@protoc_insertion_point(module_scope)
