name: Build and Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Generate Python Code
        run: |
          mkdir -p generated
          protoc --python_out=generated ./proto/*.proto
          touch generated/__init__.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build and Publish
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GH_ACTION_TOKEN }}
          TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/${{ github.repository_owner }}
        run: |
          pip install build twine
          python -m build
          twine upload --repository-url $TWINE_REPOSITORY_URL dist/*
